.TH "D:/GIT_DEV/2011_HiTech/KeyboardR/scancodes.h" 3 "Mon Mar 28 2011" "Version 0.7" "Human Interface Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/GIT_DEV/2011_HiTech/KeyboardR/scancodes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBunshifted\fP [][2]"
.br
.ti -1c
.RI "const char \fBshifted\fP [][2]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char \fBshifted\fP[][2]"
.PP
Definition at line 70 of file scancodes.h.
.SS "const char \fBunshifted\fP[][2]"
.PP
Definition at line 2 of file scancodes.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Human Interface Project from the source code.
