.TH "D:/GIT_DEV/2011_HiTech/KeyboardR/uart.c" 3 "Mon Mar 28 2011" "Version 0.7" "Human Interface Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/GIT_DEV/2011_HiTech/KeyboardR/uart.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'define.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBubrr\fP   51"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuart_init\fP (void)"
.br
.ti -1c
.RI "void \fBuart_tx\fP (unsigned int data)"
.br
.ti -1c
.RI "void \fBuart_tx_str\fP (char str[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ubrr   51"
.PP
Definition at line 2 of file uart.c.
.SH "Function Documentation"
.PP 
.SS "void uart_init (void)"
.PP
Definition at line 4 of file uart.c.
.SS "void uart_tx (unsigned intdata)"
.PP
Definition at line 16 of file uart.c.
.SS "void uart_tx_str (charstr[])"
.PP
Definition at line 23 of file uart.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Human Interface Project from the source code.
